{% set version = "0.9.5" %}
{% set python_min = "3.8" %}

package:
  name: pydoe
  version: {{ version }}

source:
    fn: pyDOE-{{ version }}.zip
    url: https://pypi.org/packages/source/p/pyDOE/pyDOE-{{ version }}.zip
    sha1: de88a5868afc5bd567fa5d590c0035fb679dcfc3c32dfc103d8f0fa02d4ac76f

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }} 
    - setuptools

  run:
    - python >={{ python_min }}
    - scipy >=1.15.3
    - numpy >=2.2.6

test:
  requires: 
    - python {{ python_min }}
  imports:
    - pyDOE

about:
  home: https://github.com/tisimst/pyDOE
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Design of experiments for Python
  description: The pyDOE package is designed to help the scientist, engineer, statistician, etc., to construct appropriate experimental designs.

extra:
  recipe-maintainers:
    - melund
    - laraibg786
