{% set version = "0.9.7" %}
{% set python_min = "3.11" %}

package:
  name: pydoe
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pydoe/pydoe-{{ version }}.tar.gz
  sha256: 73eafc0add07349111189db58fbec3cf435b88ea9bfcd6c9a0903e2db275fc26

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling >=1.26
    - hatch-vcs

  run:
    - python >={{ python_min }}
    - scipy >=1.15.3
    - numpy >=2.2.6

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyDOE

about:
  home: https://github.com/tisimst/pyDOE
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Design of experiments for Python
  description: The pyDOE package is designed to help the scientist, engineer, statistician, etc., to construct appropriate experimental designs.

extra:
  recipe-maintainers:
    - saudzahirr
    - melund
    - laraibg786
