context:
  name: pydoe
  version: 0.9.7
  python_min: 3.11

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/p/pyDOE/pyDOE-${{ version }}.zip
    sha256: 73eafc0add07349111189db58fbec3cf435b88ea9bfcd6c9a0903e2db275fc26

build:
  noarch: python
  script: python -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python ${{ python_min }} 
    - setuptools

  run:
    - python >=${{ python_min }}
    - scipy >=1.15.3
    - numpy >=2.2.6

tests:
  - python:
      imports:
        - pydoe
      pip_check: true
      python_version:
        - ${{ python_min }}.*

about:
  homepage: https://github.com/tisimst/pyDOE
  repository: https://github.com/tisimst/pyDOE
  license: BSD-3-Claus
  license_file: LICENSE
  summary: Design of experiments for Python
  description: | 
    The pyDOE package is designed to help the scientist, engineer, statistician,
    etc., to construct appropriate experimental designs.
extra:
  recipe-maintainers:
    - melund
    - laraibg786
